import { msg } from "@lingui/core/macro";
import { setI18n } from "@lingui/react/server";
import { Geist, Geist_Mono } from "next/font/google";
import type { PropsWithChildren } from "react";
import { ThemeProvider } from "@/components/theme/theme-provider";
import {
  allMessages,
  getI18nInstance,
  type PageLangParam,
} from "@/lib/i18n/appRouterI18n";
import { LinguiClientProvider } from "@/lib/i18n/LinguiClientProvider";
import linguiConfig from "~/lingui.config";
import "@/app/globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export async function generateStaticParams() {
  return linguiConfig.locales.map((lang) => ({ lang }));
}

export async function generateMetadata(props: PageLangParam) {
  const i18n = getI18nInstance((await props.params).lang);

  return {
    title: i18n._(msg`Create Next App`),
    description: i18n._(msg`Generated by create next app`),
  };
}

export default async function RootLayout({
  children,
  params,
}: PropsWithChildren<PageLangParam>) {
  const lang = (await params).lang;
  const i18n = getI18nInstance(lang);

  // @ts-ignore
  setI18n(i18n);

  return (
    <html lang={lang} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LinguiClientProvider
          initialLocale={lang}
          initialMessages={allMessages[lang]}
        >
          <ThemeProvider>{children}</ThemeProvider>
        </LinguiClientProvider>
      </body>
    </html>
  );
}
