import { msg } from "@lingui/core/macro";
import { setI18n } from "@lingui/react/server";
import { Liu_Jian_Mao_Cao, Sofadi_One, Yuji_Boku } from "next/font/google";
import type { PropsWithChildren } from "react";
import { LinguiClientProvider } from "@/components/language/lingui-client-provider";
import { ThemeProvider } from "@/components/theme/theme-provider";
import {
  allMessages,
  getI18nInstance,
  type PageLangParam,
} from "@/lib/i18n/appRouterI18n";
import linguiConfig from "~/lingui.config";
import "@/app/globals.css";

const sofadiOne = Sofadi_One({
  weight: "400",
  style: "normal",
});

const liuJianMaoCao = Liu_Jian_Mao_Cao({
  weight: "400",
  style: "normal",
});

const yujiBoku = Yuji_Boku({
  weight: "400",
  style: "normal",
});

// 语言到字体的映射
const fontMap: Record<string, string> = {
  zh: liuJianMaoCao.className,
  ja: yujiBoku.className,
  en: sofadiOne.className,
  pseudo: sofadiOne.className,
};

export async function generateStaticParams() {
  return linguiConfig.locales.map((lang) => ({ lang }));
}

export async function generateMetadata(props: PageLangParam) {
  const i18n = getI18nInstance((await props.params).lang);

  return {
    title: i18n._(msg`Create Next App`),
    description: i18n._(msg`Generated by create next app`),
  };
}

export default async function RootLayout({
  children,
  params,
}: PropsWithChildren<PageLangParam>) {
  const lang = (await params).lang;
  const i18n = getI18nInstance(lang);

  // @ts-ignore
  setI18n(i18n);

  // 根据语言选择字体：中文使用 zhiMangXing，日文使用 yujiBoku，其他语言使用 sofadiOne
  const fontClassName = fontMap[lang] || sofadiOne.className;

  return (
    <html lang={lang} suppressHydrationWarning>
      <body className={`${fontClassName} antialiased`}>
        <LinguiClientProvider
          initialLocale={lang}
          initialMessages={allMessages[lang]}
        >
          <ThemeProvider>{children}</ThemeProvider>
        </LinguiClientProvider>
      </body>
    </html>
  );
}
