import { msg } from "@lingui/core/macro";
import type { PropsWithChildren } from "react";
import { getI18nInstance, type PageLangParam } from "@/lib/i18n/appRouterI18n";

export async function generateMetadata(props: PageLangParam) {
  const i18n = getI18nInstance((await props.params).lang);

  return {
    title: i18n._(msg`Create Next App`),
    description: i18n._(msg`Generated by create next app`),
  };
}
export default function ResumeLayout({
  children,
}: PropsWithChildren<PageLangParam>) {
  return <div className="p-4 lg:p-16">{children}</div>;
}
